# Generated by Django 5.1 on 2024-10-26 22:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loh_gru', models.BigIntegerField(blank=True, null=True)),
                ('loa_gru', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_dia', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_esp', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fungicidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fun', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sec', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tra', models.TextField(max_length=20)),
                ('app_tra', models.TextField(max_length=20)),
                ('apm_tra', models.TextField(max_length=20)),
                ('nac_tra', models.DateField()),
                ('rut_tra', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tur', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cloracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_clo', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('ppm_clo', models.IntegerField(blank=True, null=True)),
                ('phe_clo', models.FloatField(blank=True, null=True)),
                ('hcl_clo', models.IntegerField(blank=True, null=True)),
                ('aci_clo', models.IntegerField(blank=True, null=True)),
                ('obs_clo', models.TextField(max_length=200)),
                ('bloque_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.bloque')),
            ],
        ),
        migrations.AddField(
            model_name='bloque',
            name='dia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.dia'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='especies_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.especies'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='lineas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.lineas'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='sector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.sector'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='trabajador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.trabajador'),
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_tem', models.TimeField()),
                ('pul_tem', models.FloatField(blank=True, null=True)),
                ('agu_tem', models.FloatField(blank=True, null=True)),
                ('amb_tem', models.FloatField(blank=True, null=True)),
                ('est_tem', models.FloatField(blank=True, null=True)),
                ('obs_tem', models.TextField(max_length=200)),
                ('dia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.dia')),
                ('lineas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.lineas')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.trabajador')),
                ('turnos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.turnos')),
            ],
        ),
        migrations.CreateModel(
            name='PPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_ppm', models.TimeField()),
                ('dat_ppm', models.IntegerField(blank=True, null=True)),
                ('phe_ppm', models.FloatField()),
                ('obs_ppm', models.TextField(max_length=200)),
                ('dia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.dia')),
                ('lineas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.lineas')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.trabajador')),
                ('turnos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.turnos')),
            ],
        ),
        migrations.AddField(
            model_name='bloque',
            name='turnos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.turnos'),
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_var', models.TextField(max_length=20)),
                ('especies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.especies')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_pro', models.TimeField()),
                ('cod_pro', models.IntegerField()),
                ('dof_pro', models.IntegerField(blank=True, null=True)),
                ('dor_pro', models.IntegerField(blank=True, null=True)),
                ('doa_pro', models.IntegerField(blank=True, null=True)),
                ('gas_pro', models.IntegerField(blank=True, null=True)),
                ('kil_pro', models.IntegerField(blank=True, null=True)),
                ('bin_pro', models.IntegerField(blank=True, null=True)),
                ('ren_pro', models.IntegerField(blank=True, null=True)),
                ('obs_pro', models.TextField(max_length=200)),
                ('dia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.dia')),
                ('especies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.especies')),
                ('fungicidas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.fungicidas')),
                ('lineas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.lineas')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.trabajador')),
                ('turnos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.turnos')),
                ('variedad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='Dosificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_dos', models.TimeField()),
                ('pei_dos', models.IntegerField(blank=True, null=True)),
                ('pef_dos', models.IntegerField(blank=True, null=True)),
                ('ccp_dos', models.IntegerField()),
                ('agu_dos', models.IntegerField(blank=True, null=True)),
                ('cer_dos', models.IntegerField(blank=True, null=True)),
                ('obs_dos', models.TextField(max_length=200)),
                ('dia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.dia')),
                ('especies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.especies')),
                ('fungicidas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.fungicidas')),
                ('lineas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.lineas')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.trabajador')),
                ('variedad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fungicidas.variedad')),
            ],
        ),
    ]
